---
name: gizmos_settings_screen_example
description: >-
  An example app to showcase `gizmos_settings_screen`. Uses
  `shared_preferences` to store settings in this example, but any storage system
  will work.

# Contact Info
homepage: https://gizmos.dev/
repository: https://github.com/GizmosDev/gizmos_settings_screen
issue_tracker: https://github.com/GizmosDev/gizmos_settings_screen/issues

version: 0.4.0

publish_to: "none"

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: ">=3.27.0"

dependencies:
  flutter:
    sdk: flutter

  # Using `shared_preferences` for this example.
  shared_preferences: ^2.0.5

  # Load our local `gizmos_settings_screen` package.
  gizmos_settings_screen:
    path: ../

dev_dependencies:
  # Testing
  flutter_test:
    sdk: flutter

  # Linting
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
