name: gizmos_settings_screen_example
description: >-
  An example app to showcase `gizmos_settings_screen`. Uses
  `shared_preferences` to store settings in this example, but any storage system
  will work.
version: 0.1.0-nullsafety.2
author: Dave Wood
homepage: https://gizmos.dev/
repository: https://github.com/GizmosDev/gizmos_settings_screen
issue_tracker: https://github.com/GizmosDev/gizmos_settings_screen/issues

publish_to: "none"

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Stricter than Effective Dart
  pedantic: ^1.11.0

  cupertino_icons: ^1.0.3

  # Using `shared_preferences` for this example.
  shared_preferences: ^2.0.5

  # Load our local `gizmos_settings_screen` package.
  gizmos_settings_screen:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
