name: gizmos_settings_screen
description: >-
  A Flutter package for displaying in-app settings screens with a native look and feel.

# Contact Info
homepage: https://gizmos.dev/
repository: https://github.com/GizmosDev/gizmos_settings_screen
issue_tracker: https://github.com/GizmosDev/gizmos_settings_screen/issues

version: 0.1.0-nullsafety.2

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: ">=3.27.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  # Testing
  flutter_test:
    sdk: flutter

  # Linting
  flutter_lints: ^6.0.0

flutter:
  generate: true
